USE mypractice;

-- Creating Table StudentInfo
CREATE TABLE STUDENTINFO
(
ROLL_NO INT NOT NULL PRIMARY KEY,
NAME VARCHAR(50),
ADDRESS VARCHAR(50),
PHONE LONG,
AGE INT);

-- Inserting Values in StudentInfo table
INSERT INTO STUDENTINFO VALUES(1,"HARSH","DELHI",9432571338,18);
INSERT INTO STUDENTINFO VALUES(2,"PRATIK","BIHAR",9157829871,19);
INSERT INTO STUDENTINFO VALUES(3,"RIYANKA","SILIGURI",9765348268,20);
INSERT INTO STUDENTINFO VALUES(4,"DEEP","RAMNAGAR",9387519645,18);
INSERT INTO STUDENTINFO VALUES(5,"SAPTARHI","KOLKATA",9563487256,19);
INSERT INTO STUDENTINFO VALUES(6,"DHANRAJ","BARABAJAR",8723465123,20);
INSERT INTO STUDENTINFO VALUES(7,"ROHIT","BALURGHAT",9822344567,18);
INSERT INTO STUDENTINFO VALUES(8,"NIRAJ","ALIPUR",9278556297,19);

-- Displaying StudentInfo table
SELECT * FROM STUDENTINFO;

-- Creating StudentCourse table
CREATE TABLE STUDENTCOURSE
( 
COURSE_ID INT,
ROLL_NO INT
);


-- Inserting data in StudentCourse table
INSERT INTO STUDENTCOURSE VALUES(1,1);
INSERT INTO STUDENTCOURSE VALUES(2,2);
INSERT INTO STUDENTCOURSE VALUES(2,3);
INSERT INTO STUDENTCOURSE VALUES(3,4);
INSERT INTO STUDENTCOURSE VALUES(1,5);
INSERT INTO STUDENTCOURSE VALUES(4,9);
INSERT INTO STUDENTCOURSE VALUES(5,10);
INSERT INTO STUDENTCOURSE VALUES(4,11);

-- Displaying StudentCourse table
SELECT * FROM STUDENTCOURSE;

-- Performing Inner Join
SELECT STUDENTINFO.NAME,STUDENTINFO.ADDRESS,STUDENTCOURSE.COURSE_ID
FROM STUDENTINFO INNER JOIN STUDENTCOURSE
ON STUDENTINFO.ROLL_NO=STUDENTCOURSE.ROLL_NO;

-- Performing Left Join
SELECT STUDENTCOURSE.COURSE_ID , STUDENTINFO.NAME,STUDENTINFO.ADDRESS
FROM STUDENTINFO
LEFT JOIN STUDENTCOURSE
ON STUDENTINFO.ROLL_NO=STUDENTCOURSE.ROLL_NO;

-- Performing Right Join
SELECT STUDENTCOURSE.COURSE_ID,STUDENTINFO.NAME,STUDENTINFO.ADDRESS
FROM STUDENTINFO
RIGHT JOIN STUDENTCOURSE
ON STUDENTINFO.ROLL_NO=STUDENTCOURSE.ROLL_NO;

-- Performing Cartesian Join OR Cross Join
SELECT STUDENTCOURSE.COURSE_ID , STUDENTINFO.NAME,STUDENTINFO.ADDRESS
FROM STUDENTINFO
CROSS JOIN STUDENTCOURSE;

-- Performing Self Join
SELECT A.ROLL_NO,B.NAME
FROM STUDENTINFO A,STUDENTINFO B
WHERE A.ROLL_NO<B.ROLL_NO;